// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCb92l1XZvc9oFUBNX0QwKZDO-5esD618',
    appId: '1:982157457475:web:3700b467ed597f871ebcf6',
    messagingSenderId: '982157457475',
    projectId: 'goggle-signin-flutter',
    authDomain: 'goggle-signin-flutter.firebaseapp.com',
    storageBucket: 'goggle-signin-flutter.appspot.com',
    measurementId: 'G-Z6XNGGBQ5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAElags6T4QwCkCQg4RMFVenaaDUg98EtU',
    appId: '1:982157457475:android:acd8694d1d7959a91ebcf6',
    messagingSenderId: '982157457475',
    projectId: 'goggle-signin-flutter',
    storageBucket: 'goggle-signin-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjPag14kCGBm_kxyxSj8oQVia9GnK1SiE',
    appId: '1:982157457475:ios:fa9173385f623b161ebcf6',
    messagingSenderId: '982157457475',
    projectId: 'goggle-signin-flutter',
    storageBucket: 'goggle-signin-flutter.appspot.com',
    iosClientId: '982157457475-aklf4uuf1p803htvkek5t9k7hjhup1pv.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleSignFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjPag14kCGBm_kxyxSj8oQVia9GnK1SiE',
    appId: '1:982157457475:ios:fa9173385f623b161ebcf6',
    messagingSenderId: '982157457475',
    projectId: 'goggle-signin-flutter',
    storageBucket: 'goggle-signin-flutter.appspot.com',
    iosClientId: '982157457475-aklf4uuf1p803htvkek5t9k7hjhup1pv.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleSignFlutter',
  );
}
